; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Tue Feb 02 2021 22:16:00 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


