; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Thu Feb 04 2021 22:45:32 GMT-0500 (Eastern Standard Time)
M280 P0 S10 ; deploy BLTouch
