; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Tue Feb 02 2021 22:16:01 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

